# Generated by Django 4.2.3 on 2023-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_user_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
    ]
