# Generated by Django 4.2.3 on 2023-10-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_user_is_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
